language: node_js

os:
  - linux

node_js:
  - "8"

script:
  - npm install
  - npm run lint

after_succes:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: public
  target_branch: master
  on:
    branch: source
