language: node_js

os:
  - linux

node_js:
  - "lts/carbon"

install:
  - npm install

script:
  - echo "would run lint at least"

after_success:
  - npm run build

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: ./public
  target_branch: master
  on:
    branch: source
