language: node_js

os:
  - linux

node_js:
  - "8"

install:
  - npm install

script:
  - npm run lint

after_success:
  - npm run build
  - ls

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: ./public
  target_branch: master
  on:
    branch: source
